### ISSUE TITLE
am-analytics container killed shortly after start

### ISSUE THREAD

**Issue by HolySamosa** [wso2/docker-apim#107]
**Description:**

When running `docker-compose` from `APIM-ISasKM-with-Analytics`, the am-analytics container ends with `Killed` after a few minutes.  Looking at the log file, the cause isn't obvious.  

```
JAVA_HOME environment variable is set to /home/wso2carbon/java
CARBON_HOME environment variable is set to /home/wso2carbon/wso2am-analytics-2.1.0
Loading spark environment variables 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[2018-03-22 17:17:14,574]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Starting WSO2 Carbon...
[2018-03-22 17:17:14,588]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Operating System : Linux 4.9.60-linuxkit-aufs, amd64
[2018-03-22 17:17:14,588]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Home        : /home/wso2carbon/java/jre
[2018-03-22 17:17:14,588]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Version     : 1.8.0_161
[2018-03-22 17:17:14,588]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.161-b12,Oracle Corporation
[2018-03-22 17:17:14,589]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Carbon Home      : /home/wso2carbon/wso2am-analytics-2.1.0
[2018-03-22 17:17:14,589]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Temp Dir    : /home/wso2carbon/wso2am-analytics-2.1.0/tmp
[2018-03-22 17:17:14,591]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  User             : wso2carbon, en-US, Etc/UTC
[2018-03-22 17:17:15,266]  INFO {org.wso2.carbon.event.output.adapter.kafka.internal.ds.KafkaEventAdapterServiceDS} -  Successfully deployed the Kafka output event adaptor service
[2018-03-22 17:17:15,415]  INFO {org.wso2.carbon.event.processor.manager.core.internal.util.ManagementModeConfigurationLoader} -  CEP started in Single node mode
[2018-03-22 17:17:15,608]  INFO {org.wso2.carbon.event.template.manager.core.internal.ds.TemplateDeployerServiceTrackerDS} -  Successfully deployed the execution manager tracker service
[2018-03-22 17:17:24,651]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} -  Started Binary SSL Transport on port : 9712
[2018-03-22 17:17:24,687]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} -  Started Binary TCP Transport on port : 9612
[2018-03-22 17:17:24,782]  INFO {org.wso2.carbon.databridge.core.internal.DataBridgeDS} -  Successfully deployed Agent Server 
[2018-03-22 17:17:26,627]  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} -  Configured Registry in 1259ms
[2018-03-22 17:17:28,617]  INFO {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} -  Registry Mode    : READ-WRITE
[2018-03-22 17:17:40,164]  INFO {org.wso2.carbon.metrics.impl.util.JmxReporterBuilder} -  Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2018-03-22 17:17:40,188]  INFO {org.wso2.carbon.metrics.impl.util.JDBCReporterBuilder} -  Creating JDBC reporter for Metrics with source 'cb2ed4608db8', data source 'jdbc/WSO2MetricsDB' and 60 seconds polling period
[2018-03-22 17:17:40,191]  INFO {org.wso2.carbon.metrics.impl.reporter.AbstractReporter} -  Started JMX reporter for Metrics
[2018-03-22 17:17:40,215]  INFO {org.wso2.carbon.metrics.impl.reporter.AbstractReporter} -  Started JDBC reporter for Metrics
[2018-03-22 17:17:58,262]  INFO {org.wso2.carbon.registry.indexing.solr.SolrClient} -  Default Embedded Solr Server Initialized
[2018-03-22 17:18:00,144]  INFO {org.wso2.carbon.user.core.internal.UserStoreMgtDSComponent} -  Carbon UserStoreMgtDSComponent activated successfully.
[2018-03-22 17:18:13,223]  INFO {org.apache.catalina.startup.TaglibUriRule} -  TLD skipped. URI: http://tiles.apache.org/tags-tiles is already defined
[2018-03-22 17:18:17,921]  INFO {org.wso2.carbon.identity.user.store.configuration.deployer.UserStoreConfigurationDeployer} -  User Store Configuration Deployer initiated.
[2018-03-22 17:18:17,922]  INFO {org.wso2.carbon.identity.user.store.configuration.deployer.UserStoreConfigurationDeployer} -  User Store Configuration Deployer initiated.
[2018-03-22 17:18:29,436]  INFO {org.wso2.carbon.core.init.CarbonServerManager} -  Repository       : /home/wso2carbon/wso2am-analytics-2.1.0/repository/deployment/server/
[2018-03-22 17:18:29,510]  INFO {org.wso2.carbon.event.input.adapter.kafka.internal.ds.KafkaEventAdapterServiceHolder} -  Kafka input event adaptor waiting for dependent configurations to load
[2018-03-22 17:18:29,743]  INFO {org.wso2.carbon.core.multitenancy.eager.TenantLoadingConfig} -  Using tenant lazy loading policy...
[2018-03-22 17:18:29,809]  INFO {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} -  Permission cache updated for tenant -1234
[2018-03-22 17:18:33,214]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-APIRequestPatternChangeAnalysisMatrixBuilder.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.stateStream:1.0.0 does not exist
[2018-03-22 17:18:33,494]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-AbnormalAccessTokenRefresh.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.allApimAlertsStream:1.0.0 does not exist
[2018-03-22 17:18:33,547]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-AbnormalRequestCountDetection-AbnormalRequestCountDetection-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.requestPerMinStream:1.0.0 does not exist
[2018-03-22 17:18:33,612]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-AbnormalResponseAndBackendTimeDetection-AbnormalResponseAndBackendTimeDetection-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.abnormalResponseTimeAlertStream:1.0.0 does not exist
[2018-03-22 17:18:33,715]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-EmailNotification.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.abnormalResponseTimeAlertStream:1.0.0 does not exist
[2018-03-22 17:18:33,743]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-FrequentTierLimitHitting-FrequentTierLimitHitting-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.tierLimitHittingAlert:1.0.0 does not exist
[2018-03-22 17:18:34,409]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-HealthAvailabilityPerMinAlert-HealthAvailabilityPerMin-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.allApimAlertsStream:1.0.0 does not exist
[2018-03-22 17:18:34,416]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-LastAccessTime.siddhiql, Dependency validation exception: Stream org.wso2.apimgt.statistics.perMinuteRequest:1.0.0 does not exist
[2018-03-22 17:18:34,469]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-MarkovStateClassifier-MarkovStateClassifier-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.apimgt.statistics.requestsPerMinPerKeyStream:1.0.0 does not exist
[2018-03-22 17:18:34,608]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-RequestPatternChangeDetection-APIRequestPatternChangeAnalysisMetric-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.allApimAlertsStream:1.0.0 does not exist
[2018-03-22 17:18:34,736]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-RequestSummarizer-RequestSummarizer-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.apimgt.statistics.perMinuteExecutionTimes:1.0.0 does not exist
[2018-03-22 17:18:34,823]  INFO {org.wso2.carbon.event.processor.core.EventProcessorDeployer} -  Execution plan deployment held back and in inactive state : APIMAnalytics-UnusualIPAccessTemplate-UnusualIPAccessAlert-realtime1.siddhiql, Dependency validation exception: Stream org.wso2.analytics.apim.allApimAlertsStream:1.0.0 does not exist
[2018-03-22 17:18:45,260]  INFO {org.springframework.web.context.support.XmlWebApplicationContext} -  Refreshing Root WebApplicationContext: startup date [Thu Mar 22 17:18:45 UTC 2018]; root of context hierarchy
[2018-03-22 17:18:45,361]  INFO {org.springframework.beans.factory.xml.XmlBeanDefinitionReader} -  Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
[2018-03-22 17:18:45,887]  INFO {org.springframework.beans.factory.xml.XmlBeanDefinitionReader} -  Loading XML bean definitions from URL [jndi:/localhost/analytics/WEB-INF/cxf-servlet.xml]
[2018-03-22 17:18:46,407]  INFO {org.springframework.beans.factory.support.DefaultListableBeanFactory} -  Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@d13691: defining beans [cxf,org.apache.cxf.bus.spring.BusWiringBeanFactoryPostProcessor,org.apache.cxf.bus.spring.Jsr250BeanPostProcessor,org.apache.cxf.bus.spring.BusExtensionPostProcessor,analyticsServices,analyticsBean,analyticsExceptionMapper,analyticsIndexExceptionMapper,analyticsTableNotFoundExceptionMapper,analyticsTimeoutExceptionMapper,jacksonJsonProvider,httpHeadersOutInterceptor]; root of factory hierarchy
[2018-03-22 17:18:51,129]  INFO {org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer} -  Deployed webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/analytics].File[/home/wso2carbon/wso2am-analytics-2.1.0/repository/deployment/server/webapps/analytics.war]
[2018-03-22 17:18:51,488]  INFO {org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer} -  Deployed webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/inputwebsocket].File[/home/wso2carbon/wso2am-analytics-2.1.0/repository/deployment/server/webapps/inputwebsocket.war]
[2018-03-22 17:19:03,214]  INFO {org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer} -  Deployed webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/outputwebsocket].File[/home/wso2carbon/wso2am-analytics-2.1.0/repository/deployment/server/webapps/outputwebsocket.war]
[2018-03-22 17:19:09,664]  INFO {org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService} -  Starting polling event receivers
[2018-03-22 17:19:27,550]  INFO {net.sf.ehcache.pool.sizeof.filter.AnnotationSizeOfFilter} -  Using regular expression provided through VM argument net.sf.ehcache.pool.sizeof.ignore.pattern for IgnoreSizeOf annotation : ^.*cache\..*IgnoreSizeOf$
[2018-03-22 17:19:27,590]  INFO {net.sf.ehcache.pool.impl.DefaultSizeOfEngine} -  Using user supplied filter @ jar:file:/home/wso2carbon/wso2am-analytics-2.1.0/repository/deployment/server/webapps/shindig/WEB-INF/lib/shindig-common-2.5.2.jar!/org/apache/shindig/common/cache/ehcache/SizeOfFilter.txt
[2018-03-22 17:19:27,706]  INFO {net.sf.ehcache.pool.sizeof.JvmInformation} -  Detected JVM data model settings of: 64-Bit HotSpot JVM with Compressed OOPs
[2018-03-22 17:19:28,355]  INFO {net.sf.ehcache.pool.sizeof.AgentLoader} -  Extracted agent jar to temporary file /home/wso2carbon/wso2am-analytics-2.1.0/tmp/ehcache-sizeof-agent3348546550869680526.jar
[2018-03-22 17:19:28,359]  INFO {net.sf.ehcache.pool.sizeof.AgentLoader} -  Trying to load agent @ /home/wso2carbon/wso2am-analytics-2.1.0/tmp/ehcache-sizeof-agent3348546550869680526.jar
[2018-03-22 17:19:28,591]  INFO {net.sf.ehcache.pool.impl.DefaultSizeOfEngine} -  using Agent sizeof engine
Killed
```

**Affected Product Version:**
Current master branch

**Comment by ThilinaManamgoda** [comment]
@HolySamosa Probably this could be a memory issue. At least 4 GB of RAM is needed only for this process.

**Comment by DilanUA** [comment]
@HolySamosa Please do let us know if you are still having this issue even after allocating enough memory for the process to run ? We will keep in touch for a reply soon.

**Comment by simontrimboy** [comment]
I also hit this running docker Version 18.03.0-ce-rc4-mac57 with the default memory allocation which is 2 GB. Increasing RAM did the trick.

**Comment by DilanUA** [comment]
@HolySamosa Do you need further help from us on this issue ?

**Comment by HolySamosa** [comment]
@DilanUA The solution suggested by @simontrimboy (Thanks!) seems to have cleared up this issue. I'm now seeing the following, however I can address this in another ticket if appropriate:

```
api-manager_1   | [2018-03-28 20:59:26,446] ERROR - DataEndpointConnectionWorker Thrift exception
api-manager_1   | org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Thrift exception
api-manager_1   | 	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:49)
api-manager_1   | 	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:93)
api-manager_1   | 	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
api-manager_1   | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
api-manager_1   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
api-manager_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
api-manager_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
api-manager_1   | 	at java.lang.Thread.run(Thread.java:748)
api-manager_1   | Caused by: org.apache.thrift.transport.TTransportException: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
api-manager_1   | 	at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:161)
api-manager_1   | 	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:65)
api-manager_1   | 	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.send_connect(ThriftSecureEventTransmissionService.java:104)
api-manager_1   | 	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.connect(ThriftSecureEventTransmissionService.java:95)
api-manager_1   | 	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:45)
api-manager_1   | 	... 7 more
api-manager_1   | Caused by: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
api-manager_1   | 	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1551)
api-manager_1   | 	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1563)
api-manager_1   | 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
api-manager_1   | 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
api-manager_1   | 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
api-manager_1   | 	at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:159)
api-manager_1   | 	... 11 more
api-manager_1   | Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
api-manager_1   | 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
api-manager_1   | 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
api-manager_1   | 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
api-manager_1   | 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
api-manager_1   | 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
api-manager_1   | 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
api-manager_1   | 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
api-manager_1   | 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
api-manager_1   | 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
api-manager_1   | 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
api-manager_1   | 	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:757)
api-manager_1   | 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
api-manager_1   | 	... 14 more
api-manager_1   | Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
api-manager_1   | 	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
api-manager_1   | 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:270)
api-manager_1   | 	at sun.security.validator.Validator.validate(Validator.java:260)
api-manager_1   | 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
api-manager_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
api-manager_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
api-manager_1   | 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
api-manager_1   | 	... 21 more
api-manager_1   | Caused by: java.security.cert.CertPathValidatorException: signature check failed
api-manager_1   | 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
api-manager_1   | 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:223)
api-manager_1   | 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
api-manager_1   | 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
api-manager_1   | 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
api-manager_1   | 	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
api-manager_1   | 	... 27 more
api-manager_1   | Caused by: java.security.SignatureException: Signature length not correct: got 256 but was expecting 128
api-manager_1   | 	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
api-manager_1   | 	at java.security.Signature$Delegate.engineVerify(Signature.java:1223)
api-manager_1   | 	at java.security.Signature.verify(Signature.java:656)
api-manager_1   | 	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:444)
api-manager_1   | 	at sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166)
api-manager_1   | 	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147)
api-manager_1   | 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
api-manager_1   | 	... 32 more
```
