### ISSUE TITLE
log analyzer is left un-configured with analytics enabled

### ISSUE THREAD

**Issue by simontrimboy** [wso2/docker-apim#108]
**Description:**
The Log Analyzer is un-configured
 
**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
On _**master** branch_ comment out

    
    

in **carbon.xml** to avoid SSL certificate exception

`javax.net.ssl.SSLException: hostname in certificate didn't match: <api-manager> != <localhost>`

Browse to https://localhost:9443/admin/loganalyzer/overview

**Comment by DilanUA** [comment]
@simontrimboy We are looking into this. Will update you shortly.

**Comment by simontrimboy** [comment]
I have noticed it is problematic to get the log analyzer working properly behind a reverse proxy; perhaps this repo could include an example with nginx as another compose file?

```
[2018-03-27 15:03:54,280]  INFO - BasicHttpFetcher The following exception occurred when fetching https://am.dev.proxy.com/shindig/rpc?method=system.listMethods&st=-1:-1:0:*:0:0:default:1522163044: 136 ms elapsed.
[2018-03-27 15:03:54,287]  INFO - BasicHttpFetcher
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:524)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.apache.shindig.gadgets.http.BasicHttpFetcher.fetch(BasicHttpFetcher.java:359)
	at org.apache.shindig.gadgets.render.DefaultServiceFetcher.retrieveServices(DefaultServiceFetcher.java:164)
	at org.apache.shindig.gadgets.render.DefaultServiceFetcher.getServicesForContainer(DefaultServiceFetcher.java:135)
	at org.apache.shindig.gadgets.render.DefaultRpcServiceLookup$1.call(DefaultRpcServiceLookup.java:80)
	at org.apache.shindig.gadgets.render.DefaultRpcServiceLookup$1.call(DefaultRpcServiceLookup.java:78)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at org.apache.shindig.gadgets.render.DefaultRpcServiceLookup.getServicesFor(DefaultRpcServiceLookup.java:77)
	at org.apache.shindig.gadgets.config.OsapiServicesConfigContributor.addServicesConfig(OsapiServicesConfigContributor.java:69)
	at org.apache.shindig.gadgets.config.OsapiServicesConfigContributor.contribute(OsapiServicesConfigContributor.java:58)
	at org.apache.shindig.gadgets.config.DefaultConfigProcessor.contribute(DefaultConfigProcessor.java:84)
	at org.apache.shindig.gadgets.config.DefaultConfigProcessor.getConfig(DefaultConfigProcessor.java:74)
	at org.apache.shindig.gadgets.js.ConfigInjectionProcessor.process(ConfigInjectionProcessor.java:82)
	at org.apache.shindig.gadgets.js.DefaultJsProcessorRegistry.process(DefaultJsProcessorRegistry.java:56)
	at org.apache.shindig.gadgets.js.DefaultJsServingPipeline.execute(DefaultJsServingPipeline.java:41)
	at org.apache.shindig.gadgets.servlet.JsServlet.doGet(JsServlet.java:94)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.shindig.gadgets.servlet.ETagFilter.doFilter(ETagFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.shindig.common.servlet.HostFilter.doFilter(HostFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:958)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[2018-03-27 15:03:54,293] ERROR - DefaultServiceFetcher Services methods from the https://am.dev.proxy.com/shindig/rpc endpoint could not be fetched. The following error occurred: java.net.ConnectException: Connection refused (Connection refused).
[2018-03-27 15:03:55,023]  INFO - BasicHttpFetcher The following exception occurred when fetching https://am.dev.wso2.com/portal/store/carbon.super/fs/gadget/LiveLogViewer/index.xml: 1 ms elapsed.
```
