### ISSUE TITLE
WSO2 API Manager version 3.0.0 can't use custom configuration (carbon.xml)

### ISSUE THREAD

**Issue by enfi08** [wso2/docker-apim#266]
Description:
When I try to install WSO2 APM v 3.0.0 I use this command : 

`docker run --volume=<hostdirectory>carbon.xml:/home/wso2carbon/wso2am-3.0.0/repository/conf/carbon.xml -it -p 8280:8280 -p 8243:8243 -p 9443:9443 --name api-manager wso2/wso2am`

But I always get this error : 

`[2019-11-22 23:12:06,283]  INFO {org.wso2.config.mapper.ConfigParser} - Applying Configurations upon new Templates
[2019-11-22 23:12:06,291]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /home/wso2carbon/wso2am-3.0.0
[2019-11-22 23:12:07,576]  SEVERE {org.wso2.carbon.server.Main handleConfiguration} - Error while performing configuration changes 
org.wso2.config.mapper.ConfigParserException: Error while store new configurations
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:132)
	at org.wso2.carbon.server.Main.handleConfiguration(Main.java:231)
	at org.wso2.carbon.server.Main.main(Main.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.io.FileNotFoundException: /home/wso2carbon/wso2am-3.0.0/repository/conf/carbon.xml (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.wso2.config.mapper.ConfigParser.deploy(ConfigParser.java:228)
	at org.wso2.config.mapper.ConfigParser.deployAndStoreMetadata(ConfigParser.java:180)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:127)
	... 8 more
`

My real goal is to change url ip address to host ip address not using localhost
so I can access WSO2 APM in browser like this

`https://<host_ip>:9443/publisher`

not 

`https://localhost:9443/publisher`

Any Suggestion?

**Comment by chirangaalwis** [comment]
@enfi08 please refer [1] documentation for this purpose.

Also, note that since this is a query regarding API Manager's configurations, please raise such issue at the API Manager product GitHub repository [2].

Thus, closing this issue. Please feel free to re-open this issue or drop in your suggestions and concerns, if you need any further clarifications.

[1]: [WSO2 API Manager v3.0.0 Configuration Catalog](https://apim.docs.wso2.com/en/latest/Reference/ConfigCatalog/#connecting-to-the-primary-data-store)
[2]: [WSO2 API Manager product GitHub repository](https://github.com/wso2/product-apim)
