### ISSUE TITLE
Working with Observability - v2.6.0

### ISSUE THREAD

**Issue by oscarvesga** [wso2/docker-apim#307]
**Description:**
I am configuring observability in apim 2.6.0 using the following [guide ](https://docs.wso2.com/display/AM260/Working+with+Observability#exampleInvoke) but I am having the next error

```
api-manager-andina_1   | java.lang.ClassNotFoundException: org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve
api-manager-andina_1   |        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
api-manager-andina_1   |        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
api-manager-andina_1   |        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
api-manager-andina_1   |        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Affected Product Version:**
v2.6.0

**OS, DB, other environment details and versions:**    
Windows 10 
Docker Desktop 2.3.0.2

**Steps to reproduce:**
Make changes in the [guide ](https://docs.wso2.com/display/AM260/Working+with+Observability#exampleInvoke) in the local volume folder

**Comment by oscarvesga** [comment]
In the realese page I get the next info

> WSO2 API-M 2.6.0 is based on WSO2 Carbon 4.4.35 and is expected to be compatible with any of the WSO2 products that are based on any Carbon 4.4.x version...

And if you see the [valve folder](https://github.com/wso2/carbon-kernel/tree/release-4.4.35/core/org.wso2.carbon.tomcat.ext/src/main/java/org/wso2/carbon/tomcat/ext/valves) for that version, there is not a java class for RequestCorrelationIdValve. So How I can fix this error? I see that the [WSO Carbon 4.6](https://github.com/wso2/carbon-kernel/tree/v4.6.0/core/org.wso2.carbon.tomcat.ext/src/main/java/org/wso2/carbon/tomcat/ext/valves) server have the java class RequestCorrelationIdValve
