### ISSUE TITLE
Wrapped java.lang.NullPointerException (/devportal/services/utils.js#32)

### ISSUE THREAD

**Issue by aldosilva6** [wso2/docker-apim#419]
**Description:**
When I try to access devportal or publisher login page on version WSO2-AM 4.0.0 I'm facing an error:

```
csm-wso2-apim  | [2021-08-30 14:08:50,427]  INFO - StartupFinalizerServiceComponent Server           :  WSO2 API Manager-4.0.0
csm-wso2-apim  | [2021-08-30 14:08:50,428]  INFO - StartupFinalizerServiceComponent WSO2 Carbon started in 68 sec
csm-wso2-apim  | [2021-08-30 14:08:50,907]  INFO - CarbonUIServiceComponent Mgt Console URL  : https://localhost:9443/carbon/
csm-wso2-apim  | [2021-08-30 14:08:50,907]  INFO - CarbonUIServiceComponent API Developer Portal Default Context : https://localhost:9443/devportal
csm-wso2-apim  | [2021-08-30 14:08:50,908]  INFO - CarbonUIServiceComponent API Publisher Default Context : https://localhost:9443/publisher
csm-wso2-apim  | [2021-08-30 14:08:50,981]  INFO - CarbonEventManagementService Starting polling event receivers
csm-wso2-apim  | [2021-08-30 14:08:51,297]  INFO - CallHomeExecutor 
csm-wso2-apim  | ..................................
csm-wso2-apim  | There are no new updates available
csm-wso2-apim  | ..................................
csm-wso2-apim  | [2021-08-30 14:09:34,537] ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/devportal/services/utils.js#32)
csm-wso2-apim  | org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/devportal/services/utils.js#32)
csm-wso2-apim  | 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587) ~[org.jaggeryjs.scriptengine_0.14.13.jar:?]
csm-wso2-apim  | 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289) ~[org.jaggeryjs.scriptengine_0.14.13.jar:?]
csm-wso2-apim  | 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:589) [org.jaggeryjs.jaggery.core_0.14.13.jar:?]
csm-wso2-apim  | 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) [org.jaggeryjs.jaggery.core_0.14.13.jar:?]

...
csm-wso2-apim  | Caused by: java.lang.NullPointerException
csm-wso2-apim  | 	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getExternalIDPOrigin_aroundBody106(APIUtil.java:2228) ~[org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
csm-wso2-apim  | 	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getExternalIDPOrigin(APIUtil.java:2225) ~[org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
```

**Suggested Labels:**
docker-compose , APIM, devportal, publisher

**Suggested Assignees:**

**Affected Product Version:**
WSO2AM 4.0.0

**OS, DB, other environment details and versions:**    
Ubuntu 20.04.2 LTS, mysql:5.7.34, Docker 20.10.7, Docker Compose 1.25.0

**Steps to reproduce:**
- docker-compose up mysql
- docker-compose up is-as-km
- docker-compose up api-manager
- https://localhost:9443/devportal/
- https://localhost:9443/publisher/

**Related Issues:**

**Comment by aldosilva6** [comment]
The problem is the apim.analytics configuration. When put this code on deployment.toml:

```
[apim.analytics]
enable = true
config_endpoint = "https://analytics-event-auth.choreo.dev/auth/v1"
auth_token = "<on-prem-key>"
```
It generates the api-manager.xml like this:
```
    <Analytics>
        <!-- Enable Analytics for API Manager -->
        <Enabled>true</Enabled>
        <AuthToken><on-prem-key></AuthToken>

        <!-- Event publisher implementation -->
        <!-- Properties for Event publisher implementation -->

        <Properties>
            <Property name="auth.api.url">https://analytics-event-auth.choreo.dev/auth/v1</Property>
        </Properties>

    </Analytics>
```

This cause an error when docker container up:
```
csm-wso2-apim  | [2021-08-30 20:54:12,306] ERROR - APIManagerConfiguration com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </AuthToken>; expected </on-prem-key>.
csm-wso2-apim  |  at [row,col {unknown-source}]: [180,43]
csm-wso2-apim  | [2021-08-30 20:54:12,313] ERROR - APIManagerComponent Error while initializing the API manager component
csm-wso2-apim  | org.wso2.carbon.apimgt.api.APIManagementException: Error while parsing API Manager configuration: /home/wso2carbon/wso2am-4.0.0/repository/conf/api-manager.xml

```

And after I cannot access devportal and publish:
```
csm-wso2-apim  | [2021-08-30 20:34:25,572] ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/devportal/services/utils.js#32)
csm-wso2-apim  | org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/devportal/services/utils.js#32)
csm-wso2-apim  | 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587) ~[org.jaggeryjs.scriptengine_0.14.13.jar:?]
```

After I disable apim.analytics on deployment.toml everything worked
```
[apim.analytics]
enable = false
config_endpoint = "https://localhost:8080/auth/v1"
auth_token = ""
```

**Comment by tandrez** [comment]
I had the same problem and this solved it. Thank you @aldosilva6 !

**Comment by oscarvesga** [comment]
The same problem is in the `deployment.toml` file in the `apim-is-as-km-with-analytics` folder where this mis configuration is creating the same problem

https://github.com/wso2/docker-apim/blob/fa55babefa207b87162b5c6e11c00795b9595372/docker-compose/apim-is-as-km-with-analytics/conf/apim/repository/conf/deployment.toml#L111
