### ISSUE TITLE
Pattern-3 is not working along with analytics

### ISSUE THREAD

**Issue by pubudu538** [wso2/docker-apim#58]
Issue reported in https://wso2.org/jira/browse/DOCKERFILE-22

Hello guys:
I've decided to create a new issue related to DOCKERFILE-21, Because 
in some way DOCKERFILE-21 was solved with the advice of Pubudu. But the goal is more general. The goal is get running the pattern-3.
When I run the analytics in an isolated mode, then I have to run the modules in this order:
apim_rdbms started OK with docker-compose
traffic-manager_1 started OK with docker-compose
analytics_1 started OK But isolated, I mean with the @Pubudu advice.
keymanager_1 started OK with docker-compose
gateway-manager_1 started OK with docker-compose
publisher_1 failed
gateway-worker_1
store_1
(This order is given by the docker-compose sleep feature)
The error with publisher module is this:
[2017-10-16 15:03:08,763] ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://analytics:7712
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://analytics:7712
at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:99)
at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointSecurityException: Error while trying to connect to ssl://analytics:7712
at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:81)
at org.wso2.carbon.databridge.agent.client.AbstractClientPoolFactory.makeObject(AbstractClientPoolFactory.java:39)
at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1212)
at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:91)
... 6 more
Caused by: org.apache.thrift.transport.TTransportException: Could not connect to analytics on port 7712
at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:237)
at org.apache.thrift.transport.TSSLTransportFactory.getClientSocket(TSSLTransportFactory.java:169)
at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:63)
... 9 more
Caused by: java.net.UnknownHostException: analytics
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:432)
at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:233)
... 11 more
I think this could be occur by the isolated mode to run the analytics module. Because like I said before in issue DOCKERFILE-21, the carbon directory has config files that could be important to the correct working.
Appreciate your help. Thank you.

**Comment by pubudu538** [comment]
Hi Carlos,

I think you have misunderstood what I have mentioned in DOCKERFILE-21 jira issue.

Please create the docker image from the new branch and you can use the same way which you used earlier. Do not isolate analytic container. You are getting these errors due to this. 

Thank you!
Pubudu.

**Comment by pubudu538** [comment]
Resolving this based on https://wso2.org/jira/browse/DOCKERFILE-21?focusedCommentId=137778&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-137778
